name: Build and Push to Azure Container Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker Login to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and Push Docker image
        env:
          AZURE_REGISTRY_NAME: ${{ secrets.ACR_NAME }}
          IMAGE_NAME: my-app # Change as needed
          ENV_FILE: ${{ secrets.ENV }}
        run: |
          echo "$ENV_FILE" > .env
          docker build -t $AZURE_REGISTRY_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }} .
          docker push $AZURE_REGISTRY_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}
          rm .env

      - name: Azure logout
        run: az logout
